[discrete]
=== Table of Contents

[.hl-green]#*0 Introductory Part*# +
{nbsp}{nbsp}{nbsp} [.hl-green]#0.1 Purpose# +
{nbsp}{nbsp}{nbsp} [.hl-green]#0.2 Skeleton# +

[.hl-green]#*1 Informative Part*# +
{nbsp}{nbsp}{nbsp} [.hl-green]#1.1 Team Members# +
{nbsp}{nbsp}{nbsp} [.hl-green]#1.2 Current Situation, Needs, Ideas# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#1.2.1 Current Situation# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#1.2.2 Needs# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#1.2.3 Ideas# +
{nbsp}{nbsp}{nbsp} [.hl-green]#1.3 Scope, Span, and Synopsis# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#1.3.1 Scope and Span# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#1.3.2 Synopsis# +
{nbsp}{nbsp}{nbsp} [.hl-green]#1.4 Other activities than just developing source code# +
{nbsp}{nbsp}{nbsp} [.hl-green]#1.5 Derived Goals# +

[.hl-green]#*2 Descriptive Part*# +
{nbsp}{nbsp}{nbsp} [.hl-green]#2.1 Domain Description# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.1.1 Rough Sketch# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.1.2 Terminology# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.1.3 Relationship Between Rough Sketch and Terminology# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.1.4 Expanded Narrative# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.1.5 Unified Domain Concepts and Operations# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.1.6 Function Signatures (Grouped with Actions)# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.1.7 Identifying Carrier Sets and Operations for Core# +
{nbsp}{nbsp}{nbsp} [.hl-green]#2.2 Requirements# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.2.1 User Stories, Epics, Features# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.2.2 Personas# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.2.3 Domain Requirements# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.2.4 Interface Requirements# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.2.5 Machine Requirements# +
{nbsp}{nbsp}{nbsp} [.hl-green]#2.3 Implementation# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#2.3.1 Selected Fragments of Implementation# +

[.hl-green]#*3 Analytic Part*# +
{nbsp}{nbsp}{nbsp} [.hl-green]#3.1 Concept Analysis# +
{nbsp}{nbsp}{nbsp} [.hl-green]#3.2 Validation and Verification# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#3.2.1 Narrative Assessment of Organizational Risks in Tournament Management# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#3.2.2 Risk Tree and Analysis for Team Creation# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#3.2.3 Risk Analysis Tree for Tournaments# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#3.2.4 Risk Tree and Analysis for Admin Banning User Permission# +
{nbsp}{nbsp}{nbsp} [.hl-green]#3.4 Checking relevant properties through TLA+# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#3.4.1 TLA+ Model for Core Database Operations# +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} [.hl-green]#3.4.2 TLA+ Model for Dynamic Match Progression# +


[.hl-red]#*i. Application of Topics*# +

[.hl-green]#*i. Generative AI Use Disclosure Statement*# +

[.hl-green]#*ii. LogBook*#
