extends: default

role:
  hl-green:
    background-color: #ccffcc
    font_color: #000000

  hl-yellow:
    background-color: #fffacc
    font_color: #000000

  hl-red:
    background-color: #ffcccc
    font_color: #000000
