extends: default

table:
  cell:
    hl-green:
      background_color: ccffcc
      font_color: 000000
      padding: 3
      border_color: ccffcc

    hl-yellow:
      background_color: ffffcc
      font_color: 000000
      padding: 3
      border_color: ffffcc

    hl-red:
      background_color: ffcccc
      font_color: 000000
      padding: 3
      border_color: ffcccc
