=== Table of Contents

0 Introductory Part::
0.1 Purpose +
0.2 Skeleton +
{nbsp} +

1 Informative Part::
1.1 Team Members +
1.2 Current situation, needs ideas +
{nbsp}{nbsp}{nbsp}1.2.1 Current situation +
{nbsp}{nbsp}{nbsp}1.2.2 Needs +
{nbsp}{nbsp}{nbsp}1.2.3 Ideas +
1.3 Scope, Span, and Synopsis +
{nbsp}{nbsp}{nbsp}1.3.1 Scope and Span +
{nbsp}{nbsp}{nbsp}1.3.2 Synopsis +
1.4 Other activities than just developing source code +
1.5 Derived Goals +
{nbsp} +

2 Descriptive Part::
2.1 Domain Description +
{nbsp}{nbsp}{nbsp}2.1.1 Rough Sketch +
{nbsp}{nbsp}{nbsp}2.1.2 Terminology +
{nbsp}{nbsp}{nbsp}2.1.3 Domain Terminology in Relation to Domain Rough Sketch +
{nbsp}{nbsp}{nbsp}2.1.4 Narrative +
{nbsp}{nbsp}{nbsp}2.1.5 Events, Actions, and Behaviors +
{nbsp}{nbsp}{nbsp}2.1.6 Function Signatures +
2.2 Requirements +
{nbsp}{nbsp}{nbsp}2.2.1 User Stories, Epics, Features +
{nbsp}{nbsp}{nbsp}2.2.2 Personas +
{nbsp}{nbsp}{nbsp}2.2.3 Domain Requirements +
{nbsp}{nbsp}{nbsp}2.2.4 Interface Requirements +
{nbsp}{nbsp}{nbsp}2.2.5 Machine Requirements +
2.3 Implementation +
{nbsp}{nbsp}{nbsp}2.3.1 Selected Fragments of Implementation +
{nbsp} +

3 Analytic Part::
3.1 Concept Analysis +
3.2 Validation and Verification +
{nbsp} +

*i. LogBook*
